version: '2'

services:
  data:
   image: busybox
   user: $UID
   volumes:
     - ./src:/var/www/html/:z

  nginx:
    #image: once-we-discuss-what-registry-service-to-use
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./scraper:/var/www/html/:z
    volumes_from:
      - data
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:4.9.8-php7.2-fpm
#    build:
#      context: .
#      dockerfile: docker/php/Dockerfile
    user: $UID
    ports:
      - "9000"
    depends_on:
      - mysql
    volumes_from:
      - data
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: toor

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

#  composer:
#    image: composer
#    user: $UID
#    volumes:
#      - $PWD/scraper:/app
#    command: composer install --ignore-platform-reqs
